import { RECEIVE_POSTS, fetchPosts } from './ReceivePosts';
import { RECEIVE_CATEGORY_POSTS, fetchCategoryPosts } from './ReceiveCategoryPosts';
import { RECEIVE_CATEGORIES, fetchCategories } from './ReceiveCategories';
import { RECEIVE_COMMENTS, fetchComments } from './ReceiveComments';
import { REMOVE_COMMENT, deleteComment } from './RemoveComment';
import { REMOVE_POST, deletePost } from './RemovePost';
import { RECEIVE_POST, fetchPost } from './ReceivePost';
import { CREATE_POST, createPost } from './CreatePost';
import { VOTE_POST, votingPost } from './VotePost';
import { VOTE_COMMENT, votingComment } from './VoteComment';
import { CREATE_COMMENT, createComment} from './CreateComment';
import { UPDATE_POST, upPost } from './UpdatePost';
import { UPDATE_COMMENT, upComment } from './UpdateComment';
import { VOTE_FETCH, votingFetch } from './VoteFetch';
import { VOTE_FETCH_CATEGORY, votingFetchCategory } from './VoteFetchCategory';

export { RECEIVE_POSTS, fetchPosts };
export { RECEIVE_CATEGORY_POSTS, fetchCategoryPosts };
export { RECEIVE_CATEGORIES, fetchCategories };
export { RECEIVE_COMMENTS, fetchComments };
export { REMOVE_COMMENT, deleteComment };
export { REMOVE_POST, deletePost };
export { RECEIVE_POST, fetchPost };
export { CREATE_POST, createPost };
export { VOTE_POST, votingPost };
export { VOTE_COMMENT, votingComment };
export { CREATE_COMMENT, createComment};
export { UPDATE_POST, upPost };
export { UPDATE_COMMENT, upComment };
export { VOTE_FETCH, votingFetch };
export { VOTE_FETCH_CATEGORY, votingFetchCategory };
